# Generated by Django 5.1.6 on 2025-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(null=True, upload_to='Blogs/banners'),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='Blogs/images/'),
        ),
    ]
