
import type { Metadata } from "next";
import "./globals.css";
import Theme from "@/providers/theme-provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Mobin Developer",
  description: "Generated by mobin heydari",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <head>
        <link
          rel="icon"
          href="/icons/logo.png"
          type="image/png"
          sizes="32px"
        />
      </head>
      <body className="dark:bg-base-dark bg-base-light">
        <Theme>
          <Navbar />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}