# Generated by Django 5.1.6 on 2025-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INP', 'In Progress'), ('COM', 'Completed'), ('ARC', 'Archived')], default='NEW', help_text='Current status of the contact inquiry.', max_length=3)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Capture the visitor's IP address for security or analytics.", null=True)),
                ('user_agent', models.CharField(blank=True, help_text="Record the browser's user agent for device information.", max_length=512, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment (e.g., resume, portfolio).', null=True, upload_to='contact_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_ignored', models.BooleanField(default=True)),
                ('is_readed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
