# Generated by Django 5.1.6 on 2025-03-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(null=True, upload_to='projects/images/')),
                ('banner', models.ImageField(null=True, upload_to='projects/banners/')),
                ('video', models.FileField(null=True, upload_to='projects/videos/')),
                ('project_status', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('In Progress', 'In Progress'), ('Fnished', 'Fnished'), ('Published', 'Published')], default='In Progress', max_length=12)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateField(null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('main_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
