# Generated by Django 5.1.6 on 2025-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_skill_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published_date',
            field=models.DateField(db_index=True),
            preserve_default=False,
        ),
    ]
